### ISSUE TITLE
Abolish _ prefix

### ISSUE THREAD

**Issue by marcospassos** [yar3333/antlr4-php-workspace#2]
Nowadays, in PHP, the prefix _ is considered a bad practice inherited from times where PHP did not support property visibility.

What do you think about abolishing its use?

**Comment by yar3333** [comment]
It is a result of the fast conversion from JavaScript. I think is not very important right now. If you have time to fix - just do it. :)

**Comment by marcospassos** [comment]
It isn't indeed, I'll provide a PR to fix it later.
