### ISSUE TITLE
Unexpected context for labeled subrule

### ISSUE THREAD

**Issue by amorimjuliana** [yar3333/antlr4-php-workspace#3]
> @yar3333, I'm running some tests here with @marcospassos and sometimes some of the issues we find are not straight forward, so I'll send you them so you can take a look. Since you are familiar with the code, there is a chance you recognize the error faster than us. Meanwhile, we will keep investigating, and Marcos will provide PRs with the fixes we can do.

The issue bellow is related to labeled subrules. When using it, we've noticed that the children list includes an unexpected child context called `FooContext`.

**Grammar**
```antlr
grammar DemoParser;

root: subrule EOF ;
subrule: 'X' # Foo;
```
**Test**
```php
$lexer = new DemoLexer(CharStreams::fromString('X'));
$tokens = new CommonTokenStream($lexer);
$parser = new DemoParser($tokens);

$result = $parser->root();
```
**Result**
```
$result = {AntlrPhp\Contexts\RootContext}
    children
        0 = {AntlrPhp\Contexts\SubruleContext}
        1 = {AntlrPhp\Contexts\FooContext}
        2 = {Antlr4\Tree\TerminalNodeImpl}
```

Please let us know if we can do something to help :)

**Comment by marcospassos** [comment]
This is the most critical bug we've found so far.

**Comment by yar3333** [comment]
Thanks, I try to look inside tomorrow.

**Comment by marcospassos** [comment]
Expected `root(subrule(foo(X)), EOF)`, actual `root(subrule(), foo(X), EOF)`

**Comment by yar3333** [comment]
I push some fixes related to printing parser tree & `labeled_subrule` test. Looks like tree is "root(subrule(subrule(X)) EOF)". Any way, I dont't use labeled subrules in past :)

**Comment by amorimjuliana** [comment]
Hi @yar3333!

We've tested this case because I believe it is a pre-requisite to get the PHP target approved as it's an ANTLR4 core feature. I've run some tests using the Java target to compare against the PHP target and check what we should expect.

The ANTLR4 visualizer tool gives us a tree structure like this:

<img width="116" alt="Screen Shot 2019-06-12 at 10 36 06" src="https://user-images.githubusercontent.com/11818859/59357386-282c8200-8d01-11e9-9399-77e3224b9607.png">

And for the `RootContext`:

<img width="397" alt="Screen Shot 2019-06-12 at 11 02 52" src="https://user-images.githubusercontent.com/11818859/59357697-ac7f0500-8d01-11e9-9212-7f365b73171a.png">

On the other hand, this is what we get using the PHP target:

<img width="454" alt="Screen Shot 2019-06-12 at 11 02 42" src="https://user-images.githubusercontent.com/11818859/59358923-d6d1c200-8d03-11e9-9c8c-42382d0c49da.png">
 
You've mentioned you didn't use labeled rules in the past, but given you have ported the entire runtime, do you have any clue on where should I start looking for? I'm digging into it, but, as I've mentioned, I am not familiar with the internals, so any guidance is welcome.

Again, thanks for your support so far! :)

**Comment by yar3333** [comment]
I feel we need to run java and php in parallel and check step-by-step where are differences begin. Today I have not enought time for this. Maybe tomorrow or during next days.

**Comment by amorimjuliana** [comment]
No problem, we are working on that and I think we're getting closer to the solution. I'll keep you posted.

**Comment by marcospassos** [comment]
The PR https://github.com/yar3333/antlr4/pull/2 fix this and other bugs.

**Comment by marcospassos** [comment]
Fixed by https://github.com/yar3333/antlr4/commit/162a889c2b01a920ea8d8c3d8b48427d6be7d45c.

Thank you, @amorimjuliana!
